### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by meeseeks-code** [RahulShaw/ITPROTV-DL#14]
* Trying to log in ... *
Cookies baked!
Traceback (most recent call last):
  File "/Users/ITPROTV-DL/driver.py", line 93, in <module>
    raise e
  File "/Users/ITPROTV-DL/driver.py", line 89, in <module>
    browser.add_cookie(cookie)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 894, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: headless chrome=103.0.5060.134)

**Comment by Jim-Manolopoulos** [comment]
Hello,

open the cookies.txt file in your text editor and comment all the lines starting with “www” and “.www”. This will fix the problem.
