### ISSUE TITLE
Access to XMLHttpRequest at 'https://web.chtbl.com/track' from origin 'https://app.acilearning.com' has been blocked by CORS policy

### ISSUE THREAD

**Issue by thisismyrepo** [RahulShaw/ITPROTV-DL#22]
DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome(executable_path="C:/ChromeDriver/chromedriver.exe",

DevTools listening on ws://127.0.0.1:56179/devtools/browser/48a5a533-36a4-41d8-a4b6-cf1701f03bf8
[1210/131942.465:INFO:CONSOLE(0)] "Access to XMLHttpRequest at 'https://web.chtbl.com/track' from origin 'https://app.acilearning.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.", source: https://app.acilearning.com/login/ (0)
[1210/131943.196:INFO:CONSOLE(2)] "ZI error TypeError: Failed to fetch", source: https://app.acilearning.com/assets/elm-app.js?46d62f906f6574b15c30b1b812f8d38e1a75a59d (2)
[1210/131943.638:INFO:CONSOLE(2)] "≡ƒÉ¢ [safeNative] Unable to access an IFrame context, using default property.", source: https://script.hotjar.com/modules.0ef46a83101151841364.js (2)
[1210/131943.646:INFO:CONSOLE(2)] "≡ƒÉ¢ [safeNative] Unable to access an IFrame context, using default property.", source: https://script.hotjar.com/modules.0ef46a83101151841364.js (2)
[1210/131943.679:INFO:CONSOLE(2)] "≡ƒÉ¢ [safeNative] Unable to access an IFrame context, using default property.", source: https://script.hotjar.com/modules.0ef46a83101151841364.js (2)
[1210/131943.680:INFO:CONSOLE(2)] "≡ƒÉ¢ [safeNative] Unable to access an IFrame context, using default property.", source: https://script.hotjar.com/modules.0ef46a83101151841364.js (2)
[1210/131943.681:INFO:CONSOLE(2)] "≡ƒÉ¢ [safeNative] Unable to access an IFrame context, using default property.", source: https://script.hotjar.com/modules.0ef46a83101151841364.js (2)
[1210/131943.683:INFO:CONSOLE(2)] "≡ƒÉ¢ [safeNative] Unable to access an IFrame context, using default property.", source: https://script.hotjar.com/modules.0ef46a83101151841364.js (2)
[1210/131943.684:INFO:CONSOLE(2)] "≡ƒÉ¢ [safeNative] Unable to access an IFrame context, using default property.", source: https://script.hotjar.com/modules.0ef46a83101151841364.js (2)
[1210/131944.383:INFO:CONSOLE(0)] "Access to XMLHttpRequest at 'https://web.chtbl.com/track' from origin 'https://app.acilearning.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.", source: https://app.acilearning.com/login?redirect_to=%2Fcourse%2Fcertified-ethical-hacker-v12%2Fcourse-overview-9050 (0)
Executing for https://app.acilearning.com/course/certified-ethical-hacker-v12/course-overview-9050
[1210/131945.191:INFO:CONSOLE(2)] "FormComplete Script Loaded!", source: https://app.acilearning.com/assets/elm-app.js?46d62f906f6574b15c30b1b812f8d38e1a75a59d (2)
[1210/131945.564:INFO:CONSOLE(2)] "WebSights Script Loaded!", source: https://app.acilearning.com/assets/elm-app.js?46d62f906f6574b15c30b1b812f8d38e1a75a59d (2)
* Trying to log in ... *
Cookies baked!
Traceback (most recent call last):
  File "C:\Users\ourde\Documents\ITPROTV-DL-master\driver.py", line 93, in <module>
    raise e
  File "C:\Users\ourde\Documents\ITPROTV-DL-master\driver.py", line 89, in <module>
    browser.add_cookie(cookie)
  File "C:\Users\ourde\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 1131, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "C:\Users\ourde\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ourde\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: headless chrome=119.0.6045.200)
Stacktrace:
        GetHandleVerifier [0x00007FF6F4588EF2+54786]
        (No symbol) [0x00007FF6F44F5612]
        (No symbol) [0x00007FF6F43AA64B]
        (No symbol) [0x00007FF6F43AEEC1]
        (No symbol) [0x00007FF6F43B115F]
        (No symbol) [0x00007FF6F43B1250]
        (No symbol) [0x00007FF6F442723C]
        (No symbol) [0x00007FF6F4435DE9]
        (No symbol) [0x00007FF6F440BE6A]
        (No symbol) [0x00007FF6F4424D02]
        (No symbol) [0x00007FF6F440BC43]
        (No symbol) [0x00007FF6F43E0941]
        (No symbol) [0x00007FF6F43E1B84]
        GetHandleVerifier [0x00007FF6F48D7F52+3524194]
        GetHandleVerifier [0x00007FF6F492D800+3874576]
        GetHandleVerifier [0x00007FF6F4925D7F+3843215]
        GetHandleVerifier [0x00007FF6F4625086+694166]
        (No symbol) [0x00007FF6F4500A88]
        (No symbol) [0x00007FF6F44FCA94]
        (No symbol) [0x00007FF6F44FCBC2]
        (No symbol) [0x00007FF6F44ECC83]
        BaseThreadInitThunk [0x00007FF946B27344+20]
        RtlUserThreadStart [0x00007FF946E026B1+33]

**Comment by thisismyrepo** [comment]
It gives the above message for every episode enumerated, then it gives this:
2f906f6574b15c30b1b812f8d38e1a75a59d (2)
Commencing download ...
Downloading: Course Overview ...
[Errno 2] No such file or directory: 'C:\\Users\\xxxx\\Documents\\ITPROTV-DL-master\\Certified Ethical Hacker (CEH) v.12 \\1. Course Overview.mp4'
Downloading: Basic Cybersecurity Concepts ...
[Errno 2] No such file or directory: 'C:\\Users\\xxxx\\Documents\\ITPROTV-DL-master\\Certified Ethical Hacker (CEH) v.12 \\2. Basic Cybersecurity Concepts.mp4'
