### ISSUE TITLE
Not working windows 

### ISSUE THREAD

**Issue by nimesh09** [RahulShaw/ITPROTV-DL#3]
I have subscription of IT pro TV but whenever try run script, i get below error.

Traceback (most recent call last):
  File "C:\IT\driver.py", line 78, in <module>
    browser.get(url)
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: headless chrome=90.0.4430.93)

and snapshot is attached
![Screenshot (201)](https://user-images.githubusercontent.com/36756508/117535324-e7cffe80-b012-11eb-9e00-b5dd2e6abd9a.png)
 , Please help me

**Comment by RahulShaw** [comment]
Please use the command correctly, "course_link" has to replaced with the URL of the course that you'd like to download.
