### ISSUE TITLE
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch

### ISSUE THREAD

**Issue by antonywpaul** [RahulShaw/ITPROTV-DL#6]
Executing for https://app.itpro.tv/course/mta-security-fundamentals-98367-2018/overview-mta98367-2018
* Trying to log in ... *
Cookies baked!
Traceback (most recent call last):
  File "driver.py", line 93, in <module>
    raise e
  File "driver.py", line 89, in <module>
    browser.add_cookie(cookie)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 894, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: headless chrome=92.0.4515.131)

**Comment by SasukeeUchiha** [comment]
Now I get this:

```
Traceback (most recent call last):
  File "driver.py", line 77, in <module>
    browser.get("https://app.itpro.tv/login/")
  File "/home/dmvlayanga/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/dmvlayanga/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/dmvlayanga/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=90.0.4430.212)
```

**Comment by SasukeeUchiha** [comment]
Wait do you need to have google chrome installed???

**Comment by VidathD** [comment]
Same here. I managed to fix it by removing/commenting out all lines in cookies.txt that don't start with `.itpro.tv` or `app.itpro.tv`
